# Generated by Django 6.0.1 on 2026-01-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_students_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
