# Generated by Django 6.0.1 on 2026-01-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_students_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='permanent_address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='temporary_address',
            field=models.TextField(null=True),
        ),
    ]
