# Generated by Django 6.0.1 on 2026-01-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_students_permanent_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='aadhar',
            field=models.FileField(null=True, upload_to='students/aadhar/'),
        ),
        migrations.AddField(
            model_name='students',
            name='marksheet_10',
            field=models.FileField(blank=True, null=True, upload_to='students/marksheets/'),
        ),
        migrations.AddField(
            model_name='students',
            name='marksheet_11',
            field=models.FileField(blank=True, null=True, upload_to='students/marksheets/'),
        ),
        migrations.AddField(
            model_name='students',
            name='photo',
            field=models.ImageField(null=True, upload_to='students/photos/'),
        ),
        migrations.AddField(
            model_name='students',
            name='signature',
            field=models.ImageField(null=True, upload_to='students/signatures/'),
        ),
        migrations.AddField(
            model_name='students',
            name='standard',
            field=models.CharField(choices=[('8', '8th'), ('9', '9th'), ('10', '10th'), ('11', '11th'), ('11n', '11th + NEET'), ('12n', '12th + NEET')], max_length=5, null=True),
        ),
    ]
