# Generated by Django 6.0.1 on 2026-01-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_students_aadhar_students_marksheet_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='payment_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='payment_status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='pending_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='remarks',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='total_fees',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
