# Generated by Django 6.0.1 on 2026-01-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_students_amount_paid_students_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='student_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
