# Generated by Django 6.0.1 on 2026-01-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_students_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
