# Generated by Django 6.0.1 on 2026-01-20 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_students_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='aadhar',
        ),
        migrations.RemoveField(
            model_name='students',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='students',
            name='marksheet_10',
        ),
        migrations.RemoveField(
            model_name='students',
            name='marksheet_11',
        ),
        migrations.RemoveField(
            model_name='students',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='students',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='students',
            name='pending_amount',
        ),
        migrations.RemoveField(
            model_name='students',
            name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='students',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='students',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='students',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='students',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='students',
            name='temporary_address',
        ),
        migrations.RemoveField(
            model_name='students',
            name='total_fees',
        ),
        migrations.AlterField(
            model_name='students',
            name='admission',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='age',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='standard',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fees', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('pending_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('payment_date', models.DateField(null=True)),
                ('payment_status', models.CharField(max_length=20, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='app.students')),
            ],
        ),
    ]
