# Generated by Django 6.0.1 on 2026-01-21 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_students_aadhar_remove_students_amount_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feepayment',
            old_name='total_fees',
            new_name='fees',
        ),
    ]
