# Generated by Django 6.0.1 on 2026-01-21 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_total_fees_feepayment_fees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feepayment',
            old_name='fees',
            new_name='total_fees',
        ),
    ]
