# Generated by Django 6.0.1 on 2026-01-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_fees_feepayment_total_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='permanent_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='temporary_address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
