# Generated by Django 6.0.1 on 2026-01-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_students_permanent_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='aadhar',
            field=models.FileField(blank=True, null=True, upload_to='students/aadhar/'),
        ),
        migrations.AddField(
            model_name='students',
            name='marksheet_10',
            field=models.FileField(blank=True, null=True, upload_to='students/marksheets/'),
        ),
        migrations.AddField(
            model_name='students',
            name='marksheet_11',
            field=models.FileField(blank=True, null=True, upload_to='students/marksheets/'),
        ),
        migrations.AddField(
            model_name='students',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/photos/'),
        ),
        migrations.AddField(
            model_name='students',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='students/signatures/'),
        ),
    ]
