# Generated by Django 6.0.1 on 2026-01-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_students_aadhar_students_marksheet_10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('other', 'other')], max_length=10, null=True),
        ),
    ]
